name: Deploy Static Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Python
        run: sudo apt-get update && sudo apt-get install -y python3

      - name: Start Local Web Server
        run: |
          echo "Starting server on localhost:8282"
          python3 -m http.server 8282 &
          sleep 10
          curl http://localhost:8282
